### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by yilmazduygu** [yilmazduygu/matlab-final#2]
Hi Bart and Katie!
I have some issues with the analysis part; 

- I cannot figure out how to label the outliers programmatically.

- My data is only the training data (I was hoping to get the test data as well by now, but unfortunately I couldn't), that's why I am doing more basic descriptive analyses. Is that ok?

Thanks!

**Comment by kwolfert** [comment]
Are you having trouble identifying the outliers in your data or labeling them on the figure?

For figure 3, it looks like you started to search for values that are greater than three standard deviations from the mean efficiency, so I think you have the right idea for identifying outliers. The function [isoutlier](https://www.mathworks.com/help/matlab/ref/isoutlier.html?searchHighlight=isoutlier&s_tid=doc_srchtitle) would be very useful here.

**Comment by yilmazduygu** [comment]
I thought of labeling the ones in figure 1
