### ISSUE TITLE
modularity

### ISSUE THREAD

**Issue by bartkrekelberg** [yilmazduygu/matlab-final#3]
The base code looks fine, but you could improve the modularity, and the structure quite a bit and make this code more reusable. 

- [x] Separate functions for the conversion from the Medx files - a function that takes a file name or a path for instance, and a destination path for the analysis.mat

- [x] Separate functions for graphics (that take the analysis.mat file as its input) - that way you can analyze different subsets

- [x] Your functions need help sections.

**Comment by yilmazduygu** [comment]
Hi Bart!
I changed the structure a bit. Did I understand you correctly, could you check?

**Comment by bartkrekelberg** [comment]
Yes, that is the structure I had in mind. Nice work.
